#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install haproxy
echo "frontend  abdo-frontend
        bind *:80
        mode http
        default_backend abdo-backend
backend abdo-backend
        balance roundrobin
        server web-01 52.72.74.64:80 check
        server web-02 3.90.80.21:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart