#!/usr/bin/env bash
# This script is displaying "Best School" 8 times
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
i=10
j=1
while [ $j -le $i ];
do
        if [ $j = 4 ]
        then
                echo "bad luck"
        elif [ $j = 8 ]
        then
                echo "good luck"
        else
                echo "Best School"
        fi
        ((j++))


done